platform :ios, '7.0'
target 'MyNews' do
	pod 'Masonry', '~> 1.0.2'
	pod 'MJRefresh', '~> 3.1.12'
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Addition', '~> 0.1.5'
	pod 'SDWebImage', '~> 4.0.0-beta2'
	pod 'CRToast', '~> 0.0.9'
end	
